image: node:18.16.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  only:
    refs:
      - main
  stage: build
  before_script:
    - npm i --force
  script:
    - npm run build:all
  artifacts:
    expire_in: '600'
    paths:
      - dist

deploy:
  only:
    - main
  stage: deploy
  before_script:
    - npm i -g firebase-tools
  script:
    - firebase deploy --only hosting:backoffice-antd -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:backoffice-material -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:backoffice-nebular -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:backoffice-primeng -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:backoffice-tailwind -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
