image: node:18.16.0

cache:
  paths:
    - node_modules/
    - dist/

deploy_all:
  stage: deploy_all
  environment: all
  only:
    - main
  script:
    - npm install -g firebase-tools
    - npm install --force
    - npm run build:all
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
